LIB := libhda-common

SOURCES := \
	exception.cpp \

TESTS := \
	tests/test_exception.cpp \
	tests/test_pimpl_utils.cpp \

FILES := \
	/usr/lib/$(LIB).so \
	/usr/include \

include /usr/share/hda/bild/bild.mk
